### ISSUE TITLE
Epichrome app crash when accessing webcam on Catalina

### ISSUE THREAD

**Issue by chrisminett** [dmarmor/epichrome#207]
I've just upgraded to Catalina (10.15.3) from the latest version of Mojave. Accessing the webcam now causes the entire Epichrome-built app to crash (it quits with no warning and no error message; when re-opening there's a Chrome notification saying it crashed and offering to re-open pages).

We use Google Meet, and it happens as soon as the page load gets to putting the webcam viewer on screen. I've also tested this on another site, for simple steps to reproduce:

* Open an Epichrome app (seems to be the same with apps with address bar and those without address bar for single page apps)
* Navigate to https://webcamtests.com
* Wait for page to detect webcam, press the **Test my cam** button
* Chrome shows a notification asking permission for the site to access the camera (I don't get this step with Google Meet as I've previously allowed it)
* Click **Allow**
* App crashes

I've read through other issues here which mention Catalina, and I don't appear to have any of them so far, but based on those conversations it may be useful to know:
* I don't have a beta version, so this is Epichrome 2.2.4
* Apps are installed in `/Applications` (I tried `~/Applications` before Catalina and the lack of 1Password was a no-go!)
* My main Epichrome app (which I use as a full browser with address bar, tabs, etc.) is listed in System Preferences > Security > Camera, along with Chrome, but other single-page apps I've used to test this issue are not, so this doesn't seem to make a difference
* Webcam works fine in vanilla Google Chrome

**Comment by dmarmor** [comment]
Hi @chrisminett, this is fixed in 2.3.0, coming soon!

**Comment by chrisminett** [comment]
Hi @dmarmor that's great news! Is there an expected timeline for v2.3? Not being able to use Meet (in my usual browser) is quickly becoming difficult for work! I've disabled the site's access to the camera but it still crashes after I deny access in the popup.

**Comment by dmarmor** [comment]
It's hard to give an exact estimate as I have to work on this in my spare time and don't have much of that these days. But the betas are working fairly stably now, so I'm hoping just a few more weeks.

Or if you want to get access to the betas now, and also help support Epichrome's development, I'd love to have you as a Patreon patron! Here's the page in case you want to check it out:

https://www.patreon.com/bePatron?u=27108162

**Comment by chrisminett** [comment]
That's great, I'll sign up now!

**Comment by chrisminett** [comment]
Works perfectly on beta 8, and solves other issues like notifications and clicking links to open in the browser. Thanks!
Anyone else suffering this issue I suggest signing up too (remember it's a beta though!)

**Comment by talleux** [comment]
I can confirm the bug AND that its solved on 2.2.4 beta ;-)

**Comment by tommasob6** [comment]
what is a link that can crash google meet

**Comment by chrisminett** [comment]
Google Meet is available at https://meet.google.com/ but as described in the OP, the issue affected any use of the webcam in the Epichrome v2.2 Chrome engine on Catalina.

This issue was resolved by the Catalina compatibility in the Epichrome v2.3 betas, and I do not experience any camera issues in the recent v2.3 stable release.

**Comment by tommasob6** [comment]
ok so its fixed good

Il giorno mar 12 mag 2020 alle ore 11:46 Chris Minett <
notifications@github.com> ha scritto:

**Comment by dmarmor** [comment]
Yes, this should be resolved in 2.3.0. I'll close the issue, but as always if you notice problems again, let me know and I'll reopen.

**Comment by tommasob6** [comment]
ok


Il giorno mer 13 mag 2020 alle ore 01:51 dmarmor <notifications@github.com>
ha scritto:
